package com.checkmate.checkit.projectbuilder.mapper;

import java.util.Map;

/**
 * 사용자 친화적인 의존성 이름 → start.spring.io의 의존성 ID로 변환하는 매핑 유틸 클래스
 */
public class DependencyNameIdMap {

	public class DependencyNameIdMap {
		private static final Map<String, String> NAME_TO_ID = Map.ofEntries(
			Map.entry("GraalVM Native Support", "native-support"),
			Map.entry("GraphQL DGS Code Generation", "graphql-dgs-codegen"),
			Map.entry("Spring Boot DevTools", "devtools"),
			Map.entry("Lombok", "lombok"),
			Map.entry("Spring Configuration Processor", "configuration-processor"),
			Map.entry("Docker Compose Support", "docker-compose"),
			Map.entry("Spring Modulith", "modulith"),
			Map.entry("Spring Web", "web"),
			Map.entry("Spring Reactive Web", "webflux"),
			Map.entry("Spring for GraphQL", "graphql"),
			Map.entry("Rest Repositories", "data-rest"),
			Map.entry("Spring Session", "session"),
			Map.entry("Rest Repositories HAL Explorer", "hal-explorer"),
			Map.entry("Spring HATEOAS", "hateoas"),
			Map.entry("Spring Web Services", "web-services"),
			Map.entry("Jersey", "jersey"),
			Map.entry("Vaadin", "vaadin"),
			Map.entry("Netflix DGS", "dgs"),
			Map.entry("htnx", "htnx"),
			Map.entry("Thymeleaf", "thymeleaf"),
			Map.entry("Apache Freemarker", "freemarker"),
			Map.entry("Mustache", "mustache"),
			Map.entry("Groovy Templates", "groovy-templates"),
			Map.entry("JTE", "jte"),
			Map.entry("Spring Security", "security"),
			Map.entry("OAuth2 Client", "oauth2-client"),
			Map.entry("OAuth2 Authorization Server", "oauth2-authorization-server"),
			Map.entry("OAuth2 Resource Server", "oauth2-resource-server"),
			Map.entry("Spring LDAP", "ldap"),
			Map.entry("Okta", "okta"),
			Map.entry("JDBC API", "jdbc"),
			Map.entry("Spring Data JPA", "data-jpa"),
			Map.entry("Spring Data JDBC", "data-jdbc"),
			Map.entry("Spring Data R2DBC", "data-r2dbc"),
			Map.entry("MyBatis Framework", "mybatis"),
			Map.entry("Liquibase Migration", "liquibase"),
			Map.entry("Flyway Migration", "flyway"),
			Map.entry("JOOQ Access Layer", "jooq"),
			Map.entry("IBM DB2 Driver", "db2"),
			Map.entry("Apache Derby Database", "derby"),
			Map.entry("H2 Database", "h2"),
			Map.entry("HyperSQL Database", "hsqldb"),
			Map.entry("MariaDB Driver", "mariadb"),
			Map.entry("MS SQL Server Driver", "sqlserver"),
			Map.entry("MySQL Driver", "mysql"),
			Map.entry("Oracle Driver", "oracle"),
			Map.entry("PostgreSQL Driver", "postgresql"),
			Map.entry("Spring Data Redis (Access+Driver)", "data-redis"),
			Map.entry("Spring Data Reactive Redis", "data-redis-reactive"),
			Map.entry("Spring Data MongoDB", "data-mongodb"),
			Map.entry("Spring Data Reactive MongoDB", "data-mongodb-reactive"),
			Map.entry("Spring Data Elasticsearch (Access+Driver)", "data-elasticsearch"),
			Map.entry("Spring Data for Apache Cassandra", "data-cassandra"),
			Map.entry("Spring Data Reactive for Apache Cassandra", "data-cassandra-reactive"),
			Map.entry("Spring Data Couchbase", "data-couchbase"),
			Map.entry("Spring Data Reactive Couchbase", "data-couchbase-reactive"),
			Map.entry("Spring Data Neo4j", "data-neo4j"),
			Map.entry("Spring Integration", "integration"),
			Map.entry("Spring for RabbitMQ", "amqp"),
			Map.entry("Spring for RabbitMQ Streams", "amqp-streams"),
			Map.entry("Spring for Apache Kafka", "kafka"),
			Map.entry("Spring for Apache Kafka Streams", "kafka-streams"),
			Map.entry("Spring for Apache ActiveMQ 5", "activemq"),
			Map.entry("Spring for Apache ActiveMQ Artemis", "artemis"),
			Map.entry("Spring for Apache Pulsar", "pulsar"),
			Map.entry("Spring for Apache Pulsar (Reactive)", "pulsar-reactive"),
			Map.entry("WebSocket", "websocket"),
			Map.entry("RSocket", "rsocket"),
			Map.entry("Apache Camel", "camel"),
			Map.entry("Solace PubSub+", "solace"),
			Map.entry("Spring Batch", "batch"),
			Map.entry("Validation", "validation"),
			Map.entry("Java Mail Sender", "mail"),
			Map.entry("Quartz Scheduler", "quartz"),
			Map.entry("Spring Cache Abstraction", "cache"),
			Map.entry("Spring Shell", "shell"),
			Map.entry("Spring gRPC", "grpc"),
			Map.entry("Spring Boot Actuator", "actuator"),
			Map.entry("CycloneDX SBOM support", "cyclonedx"),
			Map.entry("codecentric's Spring Boot Admin (Client)", "spring-boot-admin-client"),
			Map.entry("codecentric's Spring Boot Admin (Server)", "spring-boot-admin-server"),
			Map.entry("Sentry", "sentry"),
			Map.entry("Datadog", "datadog"),
			Map.entry("Dynatrace", "dynatrace"),
			Map.entry("Influx", "influx"),
			Map.entry("Graphite", "graphite"),
			Map.entry("New Relic", "newrelic"),
			Map.entry("OTLP for metrics", "micrometer-tracing-otlp"),
			Map.entry("Prometheus", "prometheus"),
			Map.entry("Distributed Tracing", "micrometer-tracing-bridge-brave"),
			Map.entry("Wavefront", "wavefront"),
			Map.entry("Zipkin", "zipkin"),
			Map.entry("Spring REST Docs", "restdocs"),
			Map.entry("Testcontainers", "testcontainers"),
			Map.entry("Contract Verifier", "contract-verifier"),
			Map.entry("Contract Stub Runner", "contract-stub-runner"),
			Map.entry("Embedded LDAP Server", "embedded-ldap"),
			Map.entry("Cloud Bootstrap", "cloud-bootstrap"),
			Map.entry("Function", "function"),
			Map.entry("Task", "task"),
			Map.entry("Config Client", "cloud-config-client"),
			Map.entry("Config Server", "cloud-config-server"),
			Map.entry("Vault Configuration", "vault-config"),
			Map.entry("Apache Zookeeper Configuration", "zookeeper-config"),
			Map.entry("Consul Configuration", "consul-config"),
			Map.entry("Eureka Discovery Client", "eureka-client"),
			Map.entry("Eureka Server", "eureka-server"),
			Map.entry("Apache Zookeeper Discovery", "zookeeper-discovery"),
			Map.entry("Consul Discovery", "consul-discovery"),
			Map.entry("Gateway", "cloud-gateway"),
			Map.entry("Reactive Gateway", "cloud-gateway-reactive"),
			Map.entry("OpenFeign", "openfeign"),
			Map.entry("Cloud LoadBalancer", "cloud-loadbalancer"),
			Map.entry("Resilience4J", "resilience4j"),
			Map.entry("Cloud Bus", "cloud-bus"),
			Map.entry("Cloud Stream", "cloud-stream"),
			Map.entry("Config Client (TAS)", "cloud-config-client-tas"),
			Map.entry("Service Registry (TAS)", "service-registry-tas"),
			Map.entry("Governance Starter (Enterprise)", "governance-starter"),
			Map.entry("Spring Cloud Gateway Access Control (Enterprise)", "gateway-access-control"),
			Map.entry("Spring Cloud Gateway Custom (Enterprise)", "gateway-custom"),
			Map.entry("Spring Cloud Gateway GraphQL (Enterprise)", "gateway-graphql"),
			Map.entry("Spring Cloud Gateway Single Sign On (Enterprise)", "gateway-sso"),
			Map.entry("Spring Cloud Gateway Traffic Control (Enterprise)", "gateway-traffic-control"),
			Map.entry("Spring Cloud Gateway Transformation (Enterprise)", "gateway-transformation"),
			Map.entry("Azure Support", "azure-support"),
			Map.entry("Azure Active Directory", "azure-active-directory"),
			Map.entry("Azure Cosmos DB", "azure-cosmos"),
			Map.entry("Azure Key Vault", "azure-keyvault"),
			Map.entry("Azure Storage", "azure-storage"),
			Map.entry("Azure OpenAI", "azure-openai"),
			Map.entry("Azure AI Search", "azure-search"),
			Map.entry("Google Cloud Support", "gcp-support"),
			Map.entry("Google Cloud Messaging", "gcp-messaging"),
			Map.entry("Google Cloud Storage", "gcp-storage"),
			Map.entry("Anthropic Claude", "anthropic-claude"),
			Map.entry("Amazon Bedrock", "amazon-bedrock"),
			Map.entry("Amazon Bedrock Converse", "amazon-bedrock-converse"),
			Map.entry("Apache Cassandra Vector Database", "cassandra-vector"),
			Map.entry("Chroma Vector Database", "chroma-vector"),
			Map.entry("Elasticsearch Vector Database", "elasticsearch-vector"),
			Map.entry("Model Context Protocol Server", "mcp-server"),
			Map.entry("Model Context Protocol Client", "mcp-client"),
			Map.entry("Milvus Vector Database", "milvus-vector"),
			Map.entry("Mistral AI", "mistral-ai"),
			Map.entry("MongoDB Atlas Vector Database", "mongodb-vector"),
			Map.entry("Neo4j Vector Database", "neo4j-vector"),
			Map.entry("Ollama", "ollama"),
			Map.entry("OpenAI", "openai"),
			Map.entry("Oracle Vector Database", "oracle-vector"),
			Map.entry("PGvector Vector Database", "pgvector"),
			Map.entry("Pinecone Vector Database", "pinecone"),
			Map.entry("PostgresML", "postgresml"),
			Map.entry("Redis Search and Query Vector Database", "redis-vector"),
			Map.entry("MariaDB Vector Database", "mariadb-vector"),
			Map.entry("Azure Cosmos DB Vector Store", "azure-vector"),
			Map.entry("Stability AI", "stability-ai"),
			Map.entry("Transformer (ONNX) Embeddings", "onnx-transformer"),
			Map.entry("Vertex AI Gemini", "vertexai-gemini"),
			Map.entry("Vertex AI Embeddings", "vertexai-embeddings"),
			Map.entry("Qdrant Vector Database", "qdrant"),
			Map.entry("Typesense Vector Database", "typesense"),
			Map.entry("Weaviate Vector Database", "weaviate"),
			Map.entry("Markdown Document Reader", "markdown-reader"),
			Map.entry("Tika Document Reader", "tika-reader"),
			Map.entry("PDF Document Reader", "pdf-reader"),
			Map.entry("Timefold Solver", "timefold")
		);
	}

	/**
	 * 의존성 이름(String) → ID(String) 매핑 반환
	 */
	public static String getId(String name) {
		return NAME_TO_ID.get(name);
	}
}
