# OAuth 공통 설정
oauth:
  providers:
    github:
      client-id: ${GITHUB_CLIENT_ID}
      client-secret: ${GITHUB_CLIENT_SECRET}
      redirect-uri: ${GITHUB_REDIRECT_URI}
      scope: ${GITHUB_SCOPE}
      authorization-uri: https://github.com/login/oauth/authorize
      token-uri: https://github.com/login/oauth/access_token
      user-info-uri: https://api.github.com/user
      user-name-attribute: login

    gitlab:
      client-id: ${GITLAB_CLIENT_ID}
      client-secret: ${GITLAB_CLIENT_SECRET}
      redirect-uri: ${GITLAB_REDIRECT_URI}
      scope: ${GITLAB_SCOPE}
      authorization-uri: https://lab.ssafy.com/oauth/authorize
      token-uri: https://lab.ssafy.com/oauth/token
      user-info-uri: https://lab.ssafy.com/api/v4/user
      user-name-attribute: username
      api-uri: https://lab.ssafy.com/api/v4

    jira:
      client-id: ${JIRA_CLIENT_ID}
      client-secret: ${JIRA_CLIENT_SECRET}
      redirect-uri: ${JIRA_REDIRECT_URI}
      scope: ${JIRA_SCOPE}
      authorization-uri: https://auth.atlassian.com/authorize
      token-uri: https://auth.atlassian.com/oauth/token
      user-info-uri: https://api.atlassian.com/oauth/userinfo
      api-uri: https://api.atlassian.com
