services:
  vllm:
    image: vllm/vllm-openai:latest
    container_name: vllm-gemma
    runtime: nvidia
    environment:
      - HUGGING_FACE_HUB_TOKEN=${HF_TOKEN}
    volumes:
      - /home/ubuntu/models:/root/.cache/huggingface
    ports:
      - "8000:8000"
    command: >
      --model google/gemma-2b-it
      --served-model-name gemma-2b-it
      --dtype=half
      --max-model-len=2048
      --gpu-memory-utilization=0.95
    ipc: host
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    networks:
      - checkit-net

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-server
    ports:
      - "8001:8000"
    env_file:
      - .env
    depends_on:
      - vllm
    networks:
      - checkit-net

networks:
  checkit-net:
    driver: bridge
